apiVersion: v1
kind: Pod
metadata:
  name: '{{{M3_NAME}}}'
  labels:
    application: '{{{M3_NAME}}}'
spec:
  containers:
    - name: web
      image: m3ntorshipci/action-test:0.0
      ports:
        - name: web
          containerPort: 3030
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: '{{{M3_NAME}}}'
spec:
  selector:
    application: '{{{M3_NAME}}}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030      
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{{M3_NAME}}}'
  labels:
    application: '{{{M3_NAME}}}'
  annotations:
    'kubernetes.io/ingress.class': nginx
    'nginx.ingress.kubernetes.io/proxy-body-size': 20m
spec:
  rules:
    - host: '{{{M3_NAME}}}-action-test.m3ntorship.com'
      http:
        paths:
          - backend:
              serviceName: '{{{M3_NAME}}}'
              servicePort: 80
            path: /
