name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  type: 
    required: true
    description: 'typeorm connection type'

  username: 
    required: true
    description: 'db username'

  password: 
    required: true
    description: 'db password'

  host: 
    required: true
    description: 'db host'

  database: 
    required: true
    description: 'database name'

  pr_number: 
    required: true
    description: 'pr number'

  srv: 
    required: true
    description: 'whether to use srv in mongodb dbs or not'
  
  temp_resources_dir: 
    default: 'temp'
    description: 'temp directory to store compiled k8s resources before deployment'

runs:
  using: 'node12'
  main: ./dist/index.js
