name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  pr_number:
    required: true
    description: 'pr number'

  connection_string:
    required: true
    description: 'mongodb db connection string'

  deployment_path:
    required: true
    description: 'directory where k8s resources located'

  temp_resources_dir:
    default: 'temp'
    description: 'temp directory to store compiled k8s resources before deployment'

  pr_repository:
    required: true
    description: 'the repository which the PR belongs to'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.pr_number}}
    - ${{inputs.connection_string}}
    - ${{inputs.deployment_path}}
    - ${{inputs.temp_resources_dir}}
    - ${{inputs.pr_repository}}
