name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  pr_number: 
    required: true
    description: 'pr number'

  connection_string: 
    required: true
    description: 'mongodb db connection string'
  
  deployment_path: 
    required: true
    description: 'directory where k8s resources located'

  temp_resources_dir: 
    default: 'temp'
    description: 'temp directory to store compiled k8s resources before deployment'
  
  pr_repository: 
    required: true
    description: 'the repository which the PR belongs to'

runs:
  using: 'node12'
  main: ./dist/index.js
