name: store pr resources
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - run: ls ./dist
      - name: add pr
        uses: ./
        env:
          M3_NAME: 'ahmed'
        with:
          kube_config: '${{secrets.KUBE_CONFIG}}'
          connection_string: '${{secrets.CICD_DB_CONNECTION_STRING}}'
          pr_number: '3350'
          deployment_path: 'deploy/apply/live'
          temp_resources_dir: 'deploy/resources/live'
          pr_repository: '${{github.repository}}'
          author: '${{github.event.user.login}}'
          pr: '${{tojson(github.event)}}'
      - run: ls -al deploy/resources/live
